# ______________________________________________________________________________________________________________________________________________________
#        1    2     3     4     5     6     7     8     9     10    11    12    13    14    15    16
ptmins: [0.,  1,    1.5,  2,    2.5,  3,    3.5,  4,    5,    6,    7,    8,    10,   12,   16]
ptmaxs: [1,   1.5,  2,    2.5,  3,    3.5,  4,    5,    6,    7,    8,    10,   12,   16,   24]

inputFiles: [
       /home/wuct/ALICE/local/Results/BDT/k3050/pre/sigma/sp/proj/projsigma.root
]
outputDir: '/home/wuct/ALICE/local/Results/BDT/k3050'
centrality: 'k3050'

#______________________________________________________________________________________________________________________________________________________
# used for the fit
# fit options
Dmeson: 'Dzero'
FixSigma: 0
Sigma: [0.015, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02]
FixSigmaFromFile: ''
FixMean: 0
MeanFile: ''
       #    0.5-1   1-1.5  1.5-2  2-2.5  2.5-3  3-3.5  3.5-4  4-5   5-6   6-7    7-8   8-10  10-12  12-16  16-24
# NSigma4SB: [4,    4,     4,     4,     4,     4,     4,     4,    4,    4,     4,    4,    4,     4,     4]
MassMin: [  1.72, 1.72,  1.72,  1.72,  1.72,  1.72,  1.70,  1.70, 1.70, 1.70,  1.70, 1.68, 1.68,  1.68,  1.66]
MassMax: [  2.02, 2.02,  2.02,  2.02,  2.02,  2.02,  2.02,  2.04, 2.04, 2.06,  2.02, 2.06, 2.06,  2.06,  2.06]
Rebin: [    2,    2,     2,     2,     2,     2,     4,     4,    4,    4,     4,    4,    6,     8,     8]
BkgFunc: [ 'expo', 'expo', 'expo', 'expo', 'expo', 'expo', 'expo', 'expo', 'expo', 'expo', 'expo', 'expo', 'expo', 'expo', 'expo', 'expo', 'expo', 'expo', 'expo', 'expo', 'expo' ]
SgnFunc: [ 'gaussian', 'gaussian', 'gaussian', 'gaussian', 'gaussian', 'gaussian', 'gaussian', 'gaussian', 'gaussian', 'gaussian', 'gaussian', 'gaussian', 'gaussian', 'gaussian', 'gaussian', 'gaussian', 'gaussian', 'gaussian', 'gaussian', 'gaussian', 'gaussian' ]
BkgFuncVn: ['kLin', 'kLin', 'kLin', 'kLin', 'kLin', 'kLin', 'kLin', 'kLin', 'kLin', 'kLin', 'kLin', 'kLin', 'kLin', 'kLin', 'kLin', 'kLin', 'kLin', 'kLin', 'kLin', 'kLin', 'kLin' ]
# only for D0
# if `enableRef` is set to `true`,  and `ReflFile` is empty, then `ReflFile` will be aotumatically filled.
enableRef: false #reflection for D0.
# if `ReflFile` is filled, then it will use the filled one
reflFile: ''
ReflFunc: "2gaus"